import type { Dict } from "./types";

export const profileDict: Dict = {
  "prof.title": ["Profil thérapeutique", "Therapy profile", "الملف العلاجي"],
  "prof.subtitle": ["Généré automatiquement par le moteur d'analyse G_Phob", "Automatically generated by the G_Phob analysis engine", "يُنشأ تلقائيًا بواسطة محرك تحليل G_Phob"],
  "prof.emergencyContact": ["Contact d'urgence", "Emergency contact", "جهة اتصال الطوارئ"],
  "prof.yearsOld": ["ans", "years old", "سنة"],
  "prof.currentLevel": ["Niveau actuel", "Current level", "المستوى الحالي"],
  "prof.level": ["Niveau", "Level", "مستوى"],
  "prof.riskLevel": ["Niveau de risque", "Risk level", "مستوى الخطورة"],
  "prof.fearScore": ["Score de peur", "Fear score", "درجة الخوف"],
  "prof.motivationScore": ["Score de motivation", "Motivation score", "درجة الدافعية"],
  "prof.riskHigh": ["Élevé", "High", "مرتفع"],
  "prof.riskModerate": ["Modéré", "Moderate", "متوسط"],
  "prof.riskLow": ["Faible", "Low", "منخفض"],
  "prof.recommendedDifficulty": ["Difficulté d'exposition recommandée", "Recommended exposure difficulty", "صعوبة التعرض الموصى بها"],
  "prof.recommendedTherapy": [
    "Thérapie recommandée : <strong>exposition graduelle TCC en 10 paliers</strong>, 3 sessions hebdomadaires de 10 à 20 minutes, avec régulation respiratoire intégrée.",
    "Recommended therapy: <strong>gradual CBT exposure in 10 stages</strong>, 3 weekly sessions of 10 to 20 minutes, with integrated breathing regulation.",
    "العلاج الموصى به: <strong>تعرض تدريجي بالعلاج السلوكي المعرفي على 10 مراحل</strong>، 3 جلسات أسبوعية من 10 إلى 20 دقيقة، مع تنظيم تنفس مدمج.",
  ],
  "prof.globalProgress": ["Progression globale", "Overall progress", "التقدم العام"],
  "prof.levelsCompleted": [
    "{done} niveaux terminés sur 10 · {sessions} sessions",
    "{done} levels completed out of 10 · {sessions} sessions",
    "{done} مستويات مكتملة من 10 · {sessions} جلسات",
  ],
  "prof.aiReco": ["Recommandations générées par l'IA", "AI-generated recommendations", "توصيات مُولَّدة بالذكاء الاصطناعي"],
  "prof.reco1": [
    "Poursuivre l'exposition « {mission} » avec une intensité réduite de 15%.",
    "Continue the exposure “{mission}” with a 15% reduced intensity.",
    "متابعة التعرض «{mission}» بشدة مخفَّضة بنسبة 15%.",
  ],
  "prof.reco2": [
    "Ajouter un exercice de cohérence cardiaque de 3 minutes avant chaque session.",
    "Add a 3-minute heart coherence exercise before each session.",
    "إضافة تمرين تناسق القلب لمدة 3 دقائق قبل كل جلسة.",
  ],
  "prof.reco3": [
    "Planifier les sessions en fin de journée : meilleure adhérence observée (+22%).",
    "Schedule sessions at the end of the day: better adherence observed (+22%).",
    "جدولة الجلسات في نهاية اليوم: لوحظ التزام أفضل (+22%).",
  ],
  "prof.reco4": [
    "Univers personnalisé recommandé : {animal}, couleur {color}.",
    "Recommended personalised universe: {animal}, color {color}.",
    "العالم المخصص الموصى به: {animal}، اللون {color}.",
  ],
  "prof.continueTherapy": ["Continuer la thérapie", "Continue therapy", "متابعة العلاج"],
  "prof.achievements": ["Succès débloqués", "Unlocked achievements", "الإنجازات المفتوحة"],
};
