/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as TherapyRouteImport } from './routes/therapy'
import { Route as SessionLevelIdRouteImport } from './routes/session.$levelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapyRoute = TherapyRouteImport.update({
  id: '/therapy',
  path: '/therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionLevelIdRoute = SessionLevelIdRouteImport.update({
  id: '/session/$levelId',
  path: '/session/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/mood': typeof MoodRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/therapy': typeof TherapyRoute
  '/session/$levelId': typeof SessionLevelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/mood': typeof MoodRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/therapy': typeof TherapyRoute
  '/session/$levelId': typeof SessionLevelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/mood': typeof MoodRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/therapy': typeof TherapyRoute
  '/session/$levelId': typeof SessionLevelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/assessment'
    | '/auth'
    | '/dashboard'
    | '/mood'
    | '/profile'
    | '/progress'
    | '/therapy'
    | '/session/$levelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/assessment'
    | '/auth'
    | '/dashboard'
    | '/mood'
    | '/profile'
    | '/progress'
    | '/therapy'
    | '/session/$levelId'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/assessment'
    | '/auth'
    | '/dashboard'
    | '/mood'
    | '/profile'
    | '/progress'
    | '/therapy'
    | '/session/$levelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AssessmentRoute: typeof AssessmentRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  MoodRoute: typeof MoodRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  TherapyRoute: typeof TherapyRoute
  SessionLevelIdRoute: typeof SessionLevelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapy': {
      id: '/therapy'
      path: '/therapy'
      fullPath: '/therapy'
      preLoaderRoute: typeof TherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$levelId': {
      id: '/session/$levelId'
      path: '/session/$levelId'
      fullPath: '/session/$levelId'
      preLoaderRoute: typeof SessionLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AssessmentRoute: AssessmentRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  MoodRoute: MoodRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  TherapyRoute: TherapyRoute,
  SessionLevelIdRoute: SessionLevelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
